#  +----------------------------------------------------------------------
#  | Spring配置
#  +----------------------------------------------------------------------
#  | Resource:
#  +----------------------------------------------------------------------
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  # 配置在mybatis-config.xml内
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://localhost:3306/Druid?useSSL=false
  #    username: root
  #    password: root.com

  #thymeleaf配置
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    #开发时关闭缓存,不然没法看到实时页面 *** 重要 ***
    cache: false


  #uploadFileSize
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  #redis配置 缓存
  #https://segmentfault.com/a/1190000012490895
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    #连接超时时间（毫秒）
    timeout: 1000
    #生菜 not jedis
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制
        max-active: -1
        #连接池中的最小空闲连接
        max-idle: 100
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    database: 0
#  +----------------------------------------------------------------------
#  | mybatis-config的配置
#  +----------------------------------------------------------------------
#  | Resource: https://mvnrepository.com/artifact/org.mybatis.spring.boot/mybatis-spring-boot-starter
#  +----------------------------------------------------------------------
mybatis:
  #类的别名
  type-aliases-package: com.example.druid.bean
  #配置文件
  config-location: classpath:/mybatis/mybatis-config.xml
  #映射文件 (单元测试时关闭，开发+正式环境时开启)
  #mapper-locations: classpath:/mapper/*.xml


#  +----------------------------------------------------------------------
#  | mybatis翻页插件
#  +----------------------------------------------------------------------
#  | Resource: https://github.com/pagehelper/pagehelper-spring-boot
#  +----------------------------------------------------------------------
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#  +----------------------------------------------------------------------
#  | druid 配置
#  +----------------------------------------------------------------------
#  | Source:
#  +----------------------------------------------------------------------
# 打断点在单元测试中查看druid的配置是否失效
# System.out.println(dataSource.getClass());
druid:
  minIdle: 5
  initialSize: 5
  maxActive: 20
  url: jdbc:mysql://localhost:3306/Druid?useSSL=false
  username: root
  password: root.com

#网页端口
server:
  port: 8181